name: Waka Readme

on:
  schedule:
  - cron: '30 18 * * *'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-readme:
    name: Update Readme with WakaTime Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Waka Readme
        uses: athul/waka-readme@v0.3.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: Update Wakapi stats
          BAR_WIDTH: "25"
          TIME_RANGE: last_30_days
          SHOW_TIME: "True"
          SHOW_MASKED_TIME: "True"
